[project]
name = "cubby-backstage"
version = "0.1.0"
description = "The backend for cubby.website"
authors = [
    {name = "Alí Sinisterra",email = "haidarconh@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">3.13, <3.14"
dependencies = [
    "fastapi[standard] (>=0.120.0,<0.121.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
